site_name: Fakepedia
site_description: A parody encyclopedia
site_url: https://talesoftheblackmarket.github.io/my-wiki/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.highlight
    - search.suggest
  palette:
    scheme: default
  font:
    text: "Georgia"
    code: "Courier New"
extra_css:
  - stylesheets/extra.css
